### ISSUE TITLE
How do I mix `must` and native validators?

### ISSUE THREAD

**Issue by celluj34** [AlexJPotter/fluentvalidation-ts#44]
If I want to create a new validator called `beInteger`, I want to combine a few rules:

* greater than or equal to (-2) ** 31
* less than or equal to 2 ** 31 - 1
* scale 0, precision 10

Is there a way to combine the first two custom rules with the built-in `scalePrecision` validator and pass it to `must`?

**Comment by AlexJPotter** [comment]
Hi @celluj34 - I'm afraid I can't think of a way to achieve that with the current implementation. The most direct workaround for now would be to copy the code for the `scalePrecision` rule into your own function so that you can combine it with other custom logic. If you have any ideas for how we could extend the library to support this I'd love to hear them! 😃
