### ISSUE TITLE
support for async validations

### ISSUE THREAD

**Issue by ReinisV** [AlexJPotter/fluentvalidation-ts#5]
Any plans for supporting async validations in the future?

Would be super great if the [`must`](https://github.com/AlexJPotter/fluentvalidation-ts#must) validation would allow for returning a promise from the custom function (or a new, `mustAsync` was introduced), so that we could use requests to server to, for example, validate that the username is not already taken.

		this.ruleFor("userName")
		  .must(async (userName) => {
 		   // todo add request to api
		    return false;
		  })
		 .withMessage("username already taken");

**Comment by AlexJPotter** [comment]
Hi - thanks for your suggestion, it's an interesting idea, and something I think would be quite a nice addition to the current API 😃 

I'll have a think about how this might work and get back to you when I've got some ideas 👍

**Comment by AlexJPotter** [comment]
Hi @ReinisV - I know it's been a while since you raised this but I'm pleased to say I have an implementation built and ready to go 🎉 

I'm just finishing up the documentation before I push the release - I'll aim to get this done over the weekend.

Thanks again for suggesting this feature, and sorry it's taken me so long to get round to addressing it!

**Comment by AlexJPotter** [comment]
Hi @ReinisV - with the release of [version 2.2.0](https://github.com/AlexJPotter/fluentvalidation-ts/releases/tag/v2.2.0), `fluentvalidation-ts` finally has support for async validation 🎉 

I've been sure to keep 100% test coverage, but this enhancement has required some fairly significant changes under the hood, so please let me know if you find any issues at all.

I hope you enjoy the new functionality! 😃
